language: node_js
cache: npm
node_js:
  - '10'
script:
  - yarn test || travis_terminate 1;
  - yarn codecov
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      openssl aes-256-cbc -K $encrypted_d13eef7098d7_key -iv $encrypted_d13eef7098d7_iv -in .travis/deploy.key.enc -out deploy.key -d;
      chmod +x ./deploy.sh;
      eval "$(ssh-agent -s)";
      chmod 600 deploy.key;
      ssh-add deploy.key;
      ssh-keyscan 206.189.200.49 >> ~/.ssh/known_hosts;
      git remote add deploy dokku@206.189.200.49:client;
      git config --global push.default simple;
      bash deploy.sh;
    fi
